"use client";

import { useState, useCallback } from "react";
import type { CalculatorResult } from "@/lib/calculator";
import { formatCurrency } from "@/lib/calculator";

interface EmailCaptureProps {
  result: CalculatorResult;
}

export function EmailCapture({ result }: EmailCaptureProps) {
  const [copied, setCopied] = useState(false);

  const generateSummary = useCallback(() => {
    const rec = result.recommended;
    const lines = [
      "HSA/FSA Optimizer 2026 - Your Results",
      "======================================",
      "",
      `Recommended Strategy: ${rec.name}`,
      "",
      "Elections:",
    ];

    if (result.isEligibleForHSA) {
      lines.push(`  HSA Contribution: ${formatCurrency(rec.hsaElection)}`);
    } else {
      lines.push(`  Health FSA: ${formatCurrency(rec.healthFSAElection)}`);
    }
    lines.push(
      `  Dependent Care FSA: ${formatCurrency(rec.dependentCareFSAElection)}`
    );

    lines.push("");
    lines.push("Estimated Tax Savings:");
    lines.push(`  Federal: ${formatCurrency(rec.federalTaxSavings)}`);
    lines.push(`  FICA: ${formatCurrency(rec.ficaSavings)}`);
    lines.push(`  Total: ${formatCurrency(rec.totalTaxSavings)}`);
    lines.push("  (Note: State taxes not included)");

    if (rec.forfeitureRisk > 0) {
      lines.push("");
      lines.push(
        `Forfeiture Risk: ${formatCurrency(rec.forfeitureRisk)} (${rec.forfeitureRiskLevel})`
      );
    }

    lines.push("");
    lines.push("Checklist:");
    result.checklist.forEach((item, i) => {
      lines.push(`  ${i + 1}. ${item}`);
    });

    lines.push("");
    lines.push("---");
    lines.push("Generated by HSA/FSA Optimizer");
    lines.push("https://your-domain.com");
    lines.push("");
    lines.push(
      "DISCLAIMER: This is an educational estimate only. Consult a tax professional."
    );

    return lines.join("\n");
  }, [result]);

  const handleEmailClick = useCallback(() => {
    const summary = generateSummary();
    const subject = encodeURIComponent("My HSA/FSA Optimizer 2026 Results");
    const body = encodeURIComponent(summary);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }, [generateSummary]);

  const handleCopyClick = useCallback(async () => {
    const summary = generateSummary();
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textArea = document.createElement("textarea");
      textArea.value = summary;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand("copy");
      document.body.removeChild(textArea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [generateSummary]);

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  return (
    <div className="rounded-lg border border-gray-200 bg-white p-4">
      <h4 className="text-sm font-medium text-gray-900 mb-3">
        Save Your Results
      </h4>
      <div className="flex flex-wrap gap-2">
        <button
          onClick={handleEmailClick}
          className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
        >
          <svg
            className="h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
            />
          </svg>
          Email Results
        </button>

        <button
          onClick={handleCopyClick}
          className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
        >
          {copied ? (
            <>
              <svg
                className="h-4 w-4 text-green-600"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                />
              </svg>
              Copy Summary
            </>
          )}
        </button>

        <button
          onClick={handlePrint}
          className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
        >
          <svg
            className="h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"
            />
          </svg>
          Print / PDF
        </button>
      </div>
    </div>
  );
}
