import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | HSA/FSA Optimizer 2026",
  description:
    "Important disclaimer and terms of use for the HSA/FSA Money Optimizer calculator.",
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Disclaimer</h1>

      <div className="prose prose-gray max-w-none">
        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Educational Purpose Only
          </h2>
          <p className="text-gray-700 mb-4">
            The HSA/FSA Money Optimizer (&quot;Calculator&quot;) is provided for
            <strong> educational and informational purposes only</strong>. It is
            designed to help you understand potential tax savings from Health
            Savings Account (HSA), Health Flexible Spending Account (FSA), and
            Dependent Care FSA contributions.
          </p>
          <p className="text-gray-700">
            The Calculator does not provide tax, legal, financial, or insurance
            advice. Any estimates or recommendations generated by this tool are
            for illustrative purposes only and should not be relied upon as the
            sole basis for any financial decision.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Not Professional Advice
          </h2>
          <p className="text-gray-700 mb-4">
            <strong>This Calculator is NOT:</strong>
          </p>
          <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
            <li>Tax advice or tax preparation services</li>
            <li>Legal advice</li>
            <li>Financial planning or investment advice</li>
            <li>Insurance advice or recommendations</li>
            <li>A substitute for professional consultation</li>
          </ul>
          <p className="text-gray-700">
            You should consult with qualified professionals (such as a tax
            advisor, CPA, financial planner, or attorney) before making any
            decisions based on information from this Calculator.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Accuracy and Limitations
          </h2>
          <p className="text-gray-700 mb-4">
            While we strive to use accurate, up-to-date IRS limits and tax
            information:
          </p>
          <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
            <li>
              The Calculator uses 2026 IRS limits based on IRS Rev. Proc.
              2025-19 and Rev. Proc. 2025-32. These limits may change.
            </li>
            <li>
              Federal tax savings estimates do not include state or local taxes,
              which vary by jurisdiction.
            </li>
            <li>
              Your actual tax savings depend on your complete tax situation,
              which this Calculator cannot fully assess.
            </li>
            <li>
              Employer plan rules, eligibility requirements, and contribution
              limits may differ from IRS maximums.
            </li>
            <li>
              The Dependent Care FSA limit ($5,000 / $2,500 for MFS) is a
              statutory limit that may be subject to change; verify with current
              IRS guidance.
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Verify with Your Employer
          </h2>
          <p className="text-gray-700 mb-4">
            Before making open enrollment elections:
          </p>
          <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
            <li>
              Review your employer&apos;s Summary Plan Description (SPD) and
              benefits materials
            </li>
            <li>
              Confirm your plan&apos;s specific contribution limits and
              eligibility rules
            </li>
            <li>Verify FSA rollover or grace period provisions</li>
            <li>
              Check whether your health plan qualifies as a High-Deductible
              Health Plan (HDHP)
            </li>
            <li>Confirm enrollment deadlines</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            No Warranties
          </h2>
          <p className="text-gray-700">
            The Calculator is provided &quot;as is&quot; without warranties of
            any kind, either express or implied. We do not guarantee the
            accuracy, completeness, or usefulness of any information provided.
            We disclaim all liability for any errors or omissions in the
            Calculator&apos;s results or for any actions taken based on those
            results.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Privacy
          </h2>
          <p className="text-gray-700">
            All calculations are performed entirely in your web browser. We do
            not collect, store, or transmit any personal or financial
            information you enter into the Calculator. No account creation or
            login is required.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Affiliate Disclosure
          </h2>
          <p className="text-gray-700">
            This site may contain affiliate links to financial products and
            services. If you click on these links and take action (such as
            opening an account), we may receive compensation. This does not
            affect the Calculator&apos;s results or recommendations, which are
            based solely on the information you provide.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Contact
          </h2>
          <p className="text-gray-700">
            If you have questions about this disclaimer or the Calculator,
            please contact us through the appropriate channels.
          </p>
        </section>
      </div>

      <div className="mt-8 pt-8 border-t border-gray-200">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 font-medium"
        >
          <svg
            className="w-4 h-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M10 19l-7-7m0 0l7-7m-7 7h18"
            />
          </svg>
          Back to Calculator
        </Link>
      </div>
    </div>
  );
}
